### PR TITLE
Test with python 3.9 in CI, deal with some windows issues

### LINKED ISSUE #13: Modernize dependencies, squash warnings?
While working on #11, #12, I've found some things annoying.

The following warnings end up in end users test logs:

`plugin.py:168: DeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.`

- just what it says?

`PytestDeprecationWarning: direct construction of CheckLinks has been deprecated, please use CheckLinks.from_parent`

  - require whatever version introduces `from_parent`

Less pressing, but still annoying are our test cases:

`PytestExperimentalApiWarning: testdir.copy_example is an experimental api that may change over time`
  - don't use `copy_example`... just `shutil.copy` into testdir?

Finally, keeping 3.5 and 2.7 happy is annoying
  - perhaps drop them?
  - ...and start testing on `3.9-nightly`?
     - the `MutableMapping`pocalypse hits `html5lib`, `requests-cache`, etc. however
  - probably can't do both at once

### PR DESCRIPTION
**Pull request by bollwyvl**
- includes #26 (thanks @AnnaDinaburgVulikh!) 
  - fixes #13
- meta
  - updates required python to 3.6
  - update badges, keywords, and classifiers
- ci
  - adds py39 to ci matrix
    - the change from #26 is a real error there! 
  - adds some more test output
  - fixes cache locations on osx/win
  - adds restore keys for cache for partial hits
- tests
  - skips `rst`-based stuff on windows
    - double import of `pywin32`, nothing we can do!
  - adds cli tests
    - the rst _does_ get test on windows, so am okay with above skips
      - still not showing coverage for `__main__`, whatever

### CODE REVIEW

**Comment by bollwyvl** [comment]
Pretty sure win36 was just flake...

**Comment by bollwyvl** [comment]
Ok, folks: I'm not planning any further changes. Feeling pretty good about the current state of the setup!

As an aside: i had a look at testing under pypy... the cache seems to not really work, but otherwise looks good.

**Comment by AnnaDinaburgVulikh** [comment]
Hi @blink1073 , can I hope for a new release after this merge?

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
Released as 0.4.4: https://pypi.org/manage/project/pytest-check-links/release/0.4.4/

**Comment by bollwyvl** [comment]
💥 thanks all!

**Pull request merged**
